### ISSUE TITLE
Mekanism Industrial Alarm

### ISSUE THREAD

**Issue by Atschinger12** [MikaylaFischler/cc-mek-scada#343]
**Is your feature request related to a problem? Please describe.**
When the Facility has an error, the alert sound is played on CC speakers. They have only a litte range from where you can hear them.

**Describe the solution you'd like**
The Mekanism Industrial Alarm is a single block that emits a visual and audible warning. The sound can be heard from a long distance away. 
So when the alarm in the Computer is triggered, it should be configurable to emit a redstone signal as well to power the industrial alarm

**Comment by MikaylaFischler** [comment]
This can be configured on an RTU as a redstone output: https://github.com/MikaylaFischler/cc-mek-scada/wiki/RSIO

**Comment by MikaylaFischler** [comment]
Specifically, if you put an alarm on top of the RTU, you would do something like this if just for unit 1:

```lua
config.RTU_REDSTONE = {
    {
        for_reactor = 1,
        io = {
            {
                port = rsio.IO.U_ALARM,
                side = "top",
                bundled_color = nil
            }
        }
    }
}
```

Or this for the whole facility:

```lua
config.RTU_REDSTONE = {
    {
        for_reactor = 0,
        io = {
            {
                port = rsio.IO.F_ALARM,
                side = "top",
                bundled_color = nil
            }
        }
    }
}
```

**Comment by Atschinger12** [comment]
thank you very much - this is awesome
