### ISSUE TITLE
RSIO `ANY_ALARM`

### ISSUE THREAD

**Issue by SkyTheCodeMaster** [MikaylaFischler/cc-mek-scada#349]
The current way to have a redstone output trigger when any significant alarm is going off is to
have an `RSIO.F_ALARM`, and then an `RSIO.U_ALARM` per unit. This takes up a lot of unnecessary
space in the config, and can all be concised down to a single `ANY_ALARM` (Probably set for the
facility, instead of a specific unit). The `ANY_ALARM` would trigger when any condition that triggers
`F_ALARM` or `U_ALARM` is met, pretty much just an OR of the two.
The simplest way to do it (in my eyes, atleast) would be to combine
https://github.com/MikaylaFischler/cc-mek-scada/blob/4fec116e934c91ee9cc84e7cb267217e3219c464/supervisor/facility.lua#L750-L758
and
https://github.com/MikaylaFischler/cc-mek-scada/blob/4fec116e934c91ee9cc84e7cb267217e3219c464/supervisor/unitlogic.lua#L794-L800
but I'm not entirely sure.

**Comment by MikaylaFischler** [comment]
I'll be adding an active high redstone output `F_ALARM_ANY` which will convey any unit returning true from  `has_alarm_min_prio(PRIO.TIMELY)` in the facility redstone I/O control (which you correctly identified in that first code reference).
