### ISSUE TITLE
Reactor PLC not wanting to connect to Supervisor

### ISSUE THREAD

**Issue by jzburda** [MikaylaFischler/cc-mek-scada#361]
**Describe the bug**
So I don't know if I'm just stupid or if this is a bug, but;
I have a coordinator, Supervisor, and Reactor PLC.
The Reactor is about 5 chunks away from main base, but still should be within my player's chunk loading. I cannot directly force load this chunk, as I am on a server that limits doing so.
The Supervisor connects fine to the Coordinator.
However, the Supervisor will not connect or network with the PLC.

Supervisor Configuration:
https://i.imgur.com/0liVz2a.png

PLC configuration:
https://i.imgur.com/grFmp4j.png

The PLC in the log files state that it is "Timing out" and nothing else.

Edit: So it seems there is some kind of "Trusted Range" issue though the configuration states it is 0. Putting the Coordinator next to the PLC  now allows them to network.

**Comment by MikaylaFischler** [comment]
Are you using a wireless modem or an ender modem? Wireless modems have a range affected by line of sight (i.e. walls reduce it), altitude, and weather. Ender modem have infinite & cross-dimensional range.

**Comment by jzburda** [comment]
Oh yeah, that's definitely it. 
I don't understand why they decided to make it that way, but it's definitely fixed now that I got everything upgraded to ender.
