### ISSUE TITLE
RTU startup error without Redstone Configuration

### ISSUE THREAD

**Issue by rasebdon** [MikaylaFischler/cc-mek-scada#371]
**Describe the bug**
When setting up an RTU with the new configurator and only setting a Boiler. The startup crashes

**To Reproduce**
1. Install RTU
2. Setup RTU with only one boiler
3. Restart RTU
4. Startup fails

**Expected behavior**
RTU works normal with one boiler attached

**Comment by MikaylaFischler** [comment]
I need more information than "the startup crashes" to help, such as an error message. Is this a fresh configuration or did you import it?

**Comment by rasebdon** [comment]
The logs

[Wed Nov 15 22:07:36 2023] [INF] ========================================
[Wed Nov 15 22:07:36 2023] [INF] BOOTING rtu.startup v1.7.2
[Wed Nov 15 22:07:36 2023] [INF] ========================================
[Wed Nov 15 22:07:36 2023] [INF] PPM: found a modem (top)
[Wed Nov 15 22:07:36 2023] [INF] PPM: found a modem (right)
[Wed Nov 15 22:07:36 2023] [INF] PPM: found a boilerValve (boilerValve_0)
[Wed Nov 15 22:07:36 2023] [INF] =====> FATAL SOFTWARE FAULT <=====
[Wed Nov 15 22:07:36 2023] [FTL] /rtu/startup.lua:150: attempt to get length of upvalue 'rtu_redstone' (a nil value)
[Wed Nov 15 22:07:36 2023] [INF] ----------------------------------
[Wed Nov 15 22:07:36 2023] [INF] RUNTIME:          ComputerCraft 1.108.4 (Minecraft 1.20.1)
[Wed Nov 15 22:07:36 2023] [INF] LUA VERSION:      Lua 5.1
[Wed Nov 15 22:07:36 2023] [INF] APPLICATION:      rtu
[Wed Nov 15 22:07:36 2023] [INF] FIRMWARE VERSION: v1.7.2
[Wed Nov 15 22:07:36 2023] [INF] COMMS VERSION:    2.4.2
[Wed Nov 15 22:07:36 2023] [INF] GRAPHICS VERSION: 2.0.7
[Wed Nov 15 22:07:36 2023] [INF] LOCKBOX VERSION:  1.1
[Wed Nov 15 22:07:36 2023] [INF] ----------------------------------
[Wed Nov 15 22:07:36 2023] [INF] --- begin debug trace ---
stack traceback:
	...scada-common/crash.lua:42: in metamethod '__len'
	/rtu/startup.lua:150: in local 'sys_config'
	/rtu/startup.lua:502: in function </rtu/startup.lua:75>
	[C]: in function 'xpcall'
	/rtu/startup.lua:560: in main chunk
[Wed Nov 15 22:07:36 2023] [INF] --- end debug trace ---
[Wed Nov 15 22:09:21 2023] [INF] ============================

I removed the redstone configuration now and it works. I think it is only the case if the configuration and settings are fresh. I set up the RTU with all default settings

**Comment by MikaylaFischler** [comment]
Okay, I was able to reproduce that, thank you. I need to make sure it records tables when none exist on fresh setups.
