### ISSUE TITLE
Reactor-PLC not able to connect

### ISSUE THREAD

**Issue by Chinomchino** [MikaylaFischler/cc-mek-scada#384]
**Describe the bug**
It seems that Reactor-PLC does not desire to connect when the mode ID is 1 

**To Reproduce**
1. Start setting up the system starting with Reactor-PLC, the supervisor being ID 3
2. Reactor-PLC stays disconnected from supervisor

**Expected behavior**
Expected it to simply Connect upon correct Auth keys and Channels setups.

**Screenshots and Logs**
![image](https://github.com/MikaylaFischler/cc-mek-scada/assets/58937034/31d38aae-70ce-4a56-9e4e-8f8ab24b09a1)

**Comment by Chinomchino** [comment]
i must note, this seems to be an issue with all devices using the new configurator

**Comment by MikaylaFischler** [comment]
If the above does not fix your problem, please share your `reactor-plc.settings` file and your supervisor's `config.lua` file. If you want to, you can remove or change your auth key before posting, but at that point you are on the hook for being sure they match.

**Comment by Chinomchino** [comment]
it seems i was rather oblivious and caused the issue myself, i simply forgot to uncomment the AUTH keys from the supervisor

**Comment by MikaylaFischler** [comment]
Glad its figured it!
