### ISSUE TITLE
Installer support for disk installations

### ISSUE THREAD

**Issue by DarkTechnician** [MikaylaFischler/cc-mek-scada#386]
**Is your feature request related to a problem? Please describe.**
Not completely a problem. Computers are able to be placed in a disk drive, and their contents editted.

**Describe the solution you'd like**
If the installer detects that it is running on a 'DISK' computer, it could install to the disk instead of to the computer. That, or ask where the user wants to install, to.

**Additional context**
One use case, would be if normal users aren't allowed HTTP privileges, but OPs are, an OP could set up a disk drive to allow them to do the required updating and installation of things, instead of the user. (I imagine an OP sitting in a booth somewhere, with a CC computer in front of them, a disk drive connected to the back side of the computer, a block or pane of glass above the disk drive, talking to a user from the other side of the glass, about what they want done.)

**Comment by MikaylaFischler** [comment]
I do not believe HTTP permissions are something that can be given to or not to certain players or op levels. I double-checked a `computercraft-server.toml` file and I see no mention of that.

After the migration from `config.lua` files to the `.settings` files is completed for all apps, the whole directory structure can just be copied from computer to disk and back again ignoring that settings file.

That would just be copying the app, `scada-common`, `graphics`, and `lockbox`, and directories, then `initenv.lua`, `startup.lua`, and `configure.lua` from the root directory. This data could just be copied between computers and overwrite existing files, as that's most of what the installer does.

There isn't really a need for an installer  feature when it could just be a few copy commands if people want to redistribute between computers, assuming one computer had the apps in the first place. I feel like #385 is the best path towards distribution when server operators refuse to enable HTTP.

If I get the chance I could add a section to the wiki about how one would redistribute via disk with copy commands.
