### ISSUE TITLE
Additional Matrix Integrations

### ISSUE THREAD

**Issue by underscorched** [MikaylaFischler/cc-mek-scada#412]
**Is your feature request related to a problem? Please describe.**
It would be really cool to be able to integrate the Induction Matrix into more places for this software.

**Describe the solution you'd like**
- [x] Low Power Redstone Output
There could be RTU redstone outputs for low power in order to activate backup generators and shed power loads. I know #323 exists but this could be an easy and versatile way of power management.
- [x] SPS Power Failovers
While the Induction Matrix has a low enough power, waste management can fail over from the SPS to other waste management methods to preserve power. Optional, but on by default.

**Additional context**

**Comment by MikaylaFischler** [comment]
Those are cool ideas! The redstone output I can do relatively easily, but the waste will require finding some space on the UI, but should still be feasible. Thanks for the suggestions!
