### ISSUE TITLE
Some RTU's not connecting with network

### ISSUE THREAD

**Issue by Xzidental** [MikaylaFischler/cc-mek-scada#415]
**Describe the bug**
All but one RTU isnt connecting to the network with same configuration of other RTU's
**To Reproduce**
Dont know how you would replicate it.
**Expected behavior**
The RTU connecting to the network considering it has the exact same configuration.

**Screenshots and Logs**
![2024-02-16_22 36 17](https://github.com/MikaylaFischler/cc-mek-scada/assets/84990483/09406060-3479-41e6-a537-4bec31fbdd54)
Screenshot of the RTU in question.
![2024-02-16_22 36 57](https://github.com/MikaylaFischler/cc-mek-scada/assets/84990483/375446e5-7ba8-4dad-960a-7afe77fa823a)
Screenshot of a RTU thats working.
**Additional context**

**Comment by Xzidental** [comment]
Copying the RTU.lua from the one machine that doesnt connect, to the one that does changes nothing

**Comment by MikaylaFischler** [comment]
Are you using ender modems or wireless modems?

**Comment by MikaylaFischler** [comment]
An rtu.lua file copy isn't doing anything, those should all be identical. Configurations are in rtu.settings for an RTU.

**Comment by Xzidental** [comment]
I switched from wireless modems to ender, and now its working. except the RTU for waste management. 
The redstone valves arent switching from polonium the plutonion.

**Comment by MikaylaFischler** [comment]
On the flow monitor screen does it show that it sees the valves (green lights next to their names)? And did you set the pipes as redstone sensitive by right clicking them with a mekanism configurator tool? It will say redstone sensitivity turned on/off when you do in the chat

**Comment by Xzidental** [comment]
I did, and on the flow monitor is shows that both pipes are connected, but 1 pipe is open, when i switch it on the main screen it doesnt switch on the flow monitor

**Comment by MikaylaFischler** [comment]
Are you in auto waste mode or manual? The main screen controls auto mode only if you have the unit(s) set to auto waste

**Comment by Xzidental** [comment]
let me check

**Comment by Xzidental** [comment]
![2024-02-17_16 59 07](https://github.com/MikaylaFischler/cc-mek-scada/assets/84990483/b614aee5-7c5e-46a6-8882-289e04dd9df1)
This is my unit monitor
![2024-02-17_16 59 38](https://github.com/MikaylaFischler/cc-mek-scada/assets/84990483/e9a39a7b-dbc7-4dad-b432-77fc4990f238)
My main monitor
![2024-02-17_17 00 01](https://github.com/MikaylaFischler/cc-mek-scada/assets/84990483/92556760-fc0b-407c-8f33-3a304c41a6c6)
My flow monitor

**Comment by Xzidental** [comment]
Figured it out... my unit monitor had the setting set to polonium

**Comment by MikaylaFischler** [comment]
Yeah, unit monitor shows it is set to polonium, which is also reflected by the indicator to the top right of the waste processing on the main monitor. The valve states match that mode

**Comment by Xzidental** [comment]
Thanks, also i have a suggestion. do i make another thread or should i post it here

**Comment by MikaylaFischler** [comment]
If you have a feature request you can make a new issue, that would be preferable
