### ISSUE TITLE
Adding a second reactor to the supervisor crashes the coordinator.

### ISSUE THREAD

**Issue by Xzidental** [MikaylaFischler/cc-mek-scada#423]
**Describe the bug**
Basically the title. 

**To Reproduce**
1. Go to your supervisor
2. reconfigure to have 2 reactors instead of 2
3. reboot
4. womp womp
![2024-02-19_21 17 43](https://github.com/MikaylaFischler/cc-mek-scada/assets/84990483/f6edd0f9-9955-463e-89b7-1eb23d7f9885)

**Expected behavior**
A second reactor added to the system

**Screenshots and Logs**
![2024-02-19_21 19 12](https://github.com/MikaylaFischler/cc-mek-scada/assets/84990483/efaf6b03-d9f1-4b1d-8eca-0415f189b150)
![2024-02-19_21 19 12](https://github.com/MikaylaFischler/cc-mek-scada/assets/84990483/e8cf5d0f-0e3e-4615-99ac-511a75f15253)

**Additional context**
Adding a fusion reactor to the system doesnt work. when i set the reactor count in the supervisor back to 1 it boots right back up.

**Comment by MikaylaFischler** [comment]
1. Fusion reactors aren't supported
2. You have to change your coordinator's configuration if you change the unit count. That's not a crash, it is telling you your unit counts don't match. The next update will re-word that message.
