### ISSUE TITLE
Add actual rate of production to SNAs

### ISSUE THREAD

**Issue by BlockOG** [MikaylaFischler/cc-mek-scada#438]
**Is your feature request related to a problem? Please describe.**
Currently the SNAs display for polonium doesn't display the actual production rate of polonium, nor does the displayed flow coming out of it or the SPS's input rate.

**Describe the solution you'd like**
Add an `OUT` entry to the SNAs and change the flow rate on the pipes and SPS input rate to the actual rate, which can be relatively trivially calculated by doing `math.min(sna.getInput().amount / 10, sna.getProductionRate())`.

**Comment by MikaylaFischler** [comment]
Implemented in the development branch now. As a note, this reduced precision of some fields, but given that the trade-off is accuracy, I don't really mind.

I didn't add an "OUT" since it would be redundant with the pipe flow right next to it.
