### ISSUE TITLE
Screens not updating after going to different dimension

### ISSUE THREAD

**Issue by silicon11** [MikaylaFischler/cc-mek-scada#453]
**Describe the bug**
Screens not updating after going to different dimension, I have the reactor in a different dimension and when I go back to where the control room is in the overworld the screens stop updating and I have to break them (sometimes several times) until they start refreshing again. I am also having issues with the pocket computer not showing anything at all but that's another issue all together I believe.

**To Reproduce**
1. Go to 'different dimension'
2. Go back to 'control room dimension'
3. Screens aren't anymore updating.

**Expected behavior**
Screens to be updating. I know computercraft can be quirky! I am using advanced screens and computers connected with ender modems. 

**Screenshots and Logs**
Not sure what logs to include but let me know.

**Additional context**
Awesome mod!

**Comment by silicon11** [comment]
You're right I thought it was chunk loaded but it wasn't, sorry about that. Looking forward to seeing what you do with this in the future.

**Comment by MikaylaFischler** [comment]
No worries! Happy to hear that
