### ISSUE TITLE
Induction Matrix Charge/Discharge Duration ETA

### ISSUE THREAD

**Issue by aerulion** [MikaylaFischler/cc-mek-scada#469]
**Is your feature request related to a problem? Please describe.**
Sometimes I have no reactor running (during maintenance for example), and would like to know how much time I have left until the induction matrix runs out of energy.

**Describe the solution you'd like**
A simple additional line that calculates the estimated time it takes, until the Matrix runs out of energy. The same line could display the estimated duration until the matrix is completely full, if the current energy input is higher than the output.

**Additional context**
/

**Comment by MikaylaFischler** [comment]
Nice idea! I'll be able to do that!
