### ISSUE TITLE
RTU gateway error?

### ISSUE THREAD

**Issue by YUANWONGSATHORN** [MikaylaFischler/cc-mek-scada#503]
**Describe the bug**
hi i have a problem that i connect reactor unit 1-2 using turbine 1 and  reactor unit 3-4 for turbine number 2 and when i go look in the main and flow monitor it show Turbine 2 that use for reactor 3-4 offline but turbine for unit 1-2 is normal i have already try update software but it didn't work is there something i missing? can you help me?

**Screenshots and Logs**
Here what main and flow monitor show
![2024-06-27_19 03 12](https://github.com/MikaylaFischler/cc-mek-scada/assets/76692859/9fd6eb3f-11b5-493c-ac04-0a1140b23795)
![2024-06-27_19 03 19](https://github.com/MikaylaFischler/cc-mek-scada/assets/76692859/a8bf3ea5-2a6e-4d4d-93af-33dc7aec06b4)
Here is RTU gateway
![2024-06-27_19 04 00](https://github.com/MikaylaFischler/cc-mek-scada/assets/76692859/d3fed382-4a9a-405b-8639-129900010d2a)
right is turbine 1 and left is turbine 2
![2024-06-27_19 04 09](https://github.com/MikaylaFischler/cc-mek-scada/assets/76692859/03a95479-c0b4-4393-8539-83a084a2676b)

**Comment by MikaylaFischler** [comment]
The numbering of boilers and turbines is on a per-reactor basis. If you have 4 turbines split across 4 reactors (one for each) you would have four "Turbine 1"s, each assigned to a different unit.

**Comment by YUANWONGSATHORN** [comment]
> The numbering of boilers and turbines is on a per-reactor basis. If you have 4 turbines split across 4 reactors (one for each) you would have four "Turbine 1"s, each assigned to a different unit.

oh i get it Thankyou so much 🤍

**Comment by MikaylaFischler** [comment]
Great, happy to help! :)
