### ISSUE TITLE
Induction Matrix RTU wont tie to network

### ISSUE THREAD

**Issue by MsAlPatina** [MikaylaFischler/cc-mek-scada#520]
The RTU for the Induction Matrix wont connect no matter what

**To Reproduce**
1. try add an induction matrix
2. it wont connect

**Comment by MikaylaFischler** [comment]
Let me know if you still have the issue after completing these steps. https://github.com/MikaylaFischler/cc-mek-scada/wiki/FAQ-and-Common-Problems#my-computers-wont-connect-to-each-other

**Comment by MsAlPatina** [comment]
> Let me know if you still have the issue after completing these steps. https://github.com/MikaylaFischler/cc-mek-scada/wiki/FAQ-and-Common-Problems#my-computers-wont-connect-to-each-other
> 
> That is for the RTU not connecting to the network. If you mean something with the peripheral, I will need more details, like some screenshots and logs.

The log.txt shows some stuff
"[ERR] PPM: [@inductionPort_2] protected isFormed() -> Terminated"

**Comment by MikaylaFischler** [comment]
That's not helpful, that just means you terminated the application while it was checking if your induction matrix is formed. I would need you to share the whole log, such as by using `pastebin put log.txt` and giving me the link/code, or attaching it here.

Screenshots of the RTU's front panel display (main screen) would help, so please do share that.

**Comment by MsAlPatina** [comment]
https://pastebin.com/sDU280aa
![2024-07-14_16 27 44](https://github.com/user-attachments/assets/d61fb637-0ceb-4f3f-90fd-8d299500c9dd)

**Comment by MikaylaFischler** [comment]
Okay so the issue is the network side of it given that the network light is gray/off. Please refer to the items in that first link until the network light becomes green.

**Comment by MsAlPatina** [comment]
> Okay so the issue is the network side of it given that the network light is gray/off. Please refer to the items in that first link until the network light becomes green.

Alright, tho even when i removed the password it dindt work, all are using ender modems

**Comment by MikaylaFischler** [comment]
If you remove the facility key on one you would need to remove it on all of them, did you? If that fixes it, then it was typed differently on one of the devices

**Comment by MsAlPatina** [comment]
> If you remove the facility key on one you would need to remove it on all of them, did you? If that fixes it, then it was typed differently on one of the devices

it was removed on all devices, i wonder if it could possibly be other computers tampering, but i doubt, since thoose dont even interact with scada

**Comment by MsAlPatina** [comment]
At one point the network light was yellow

**Comment by MikaylaFischler** [comment]
Okay, make sure all your devices are up-to-date then. If you installed the RTU after the last update, then it would also not work even if the facility keys match (normally it wouldn't break in that way, but this time I overhauled how authenticated networking worked). I was suspecting this as I was waiting for you to try that. Make sure your supervisor (and other devices) are up-to-date. You should see `NT: v3.0.0` on all the devices.

**Comment by MsAlPatina** [comment]
> Okay, make sure all your devices are up-to-date then since you saw that yellow light. If you installed the RTU after the last update, then it would also not work even if the facility keys match (normally it wouldn't break in that way, but this time I overhauled how authenticated networking worked). I was suspecting this as I was waiting for you to try that. Make sure your supervisor (and other devices) are up-to-date. You should see `NT: v3.0.0` on all the devices.

so they cant have auth keys?

**Comment by MsAlPatina** [comment]
Scada Coordinator NT v2.5.2
supervisor 2.5.2
huh, when did it change to 3.0? im using
wget https://raw.githubusercontent.com/MikaylaFischler/cc-mek-scada/main/ccmsi.lua

**Comment by MikaylaFischler** [comment]
They can use auth keys, they just all need to be up-to-date, since the old authentication logic doesn't work with the new authentication logic. If it did, it would have shown the yellow light at least (but still prevented use due to mismatching protocol versions).

Normally when updating it gives you a warning when the comms version changes, as that requires updating all the devices so they understand what each other is saying. Installing an app fresh can't do this, since it doesn't know that the other devices aren't at the same version, which is where the yellow light comes in.

You need to do `ccmsi update supervisor`, `ccmsi update coordinator`, etc on the devices you have with those respective apps. It will also probably ask if you want to update the installer, which you should do, then you'll have to run the update command again to update the app

**Comment by MsAlPatina** [comment]
> They can use auth keys, they just all need to be up-to-date, since the old authentication logic doesn't work with the new authentication logic. If it did, it would have shown the yellow light at least (but still prevented use due to mismatching protocol versions).
> 
> Normally when updating it gives you a warning when the comms version changes, as that requires updating all the devices so they understand what each other is saying. Installing an app fresh can't do this, since it doesn't know that the other devices aren't at the same version, which is where the yellow light comes in.
> 
> You need to do `ccmsi update supervisor`, `ccmsi update coordinator`, etc on the devices you have with those respective apps. It will also probably ask if you want to update the installer, which you should do, then you'll have to run the update command again to update the app

thanks, i will keep ya updated if something breaks, also maybe make the version numbers a bit more noticeble!

**Comment by MikaylaFischler** [comment]
#364 would likely cover this in the future, as it will be able to list possible causes for a failed connection test

**Comment by MsAlPatina** [comment]
> #364 would likely cover this in the future, as it will be able to list possible causes for a failed connection test

Would be happy if i can help
