### ISSUE TITLE
Can't Update Installer when No Apps Installed

### ISSUE THREAD

**Issue by dragonsky201** [MikaylaFischler/cc-mek-scada#573]
![image_2024-11-07_214123323](https://github.com/user-attachments/assets/02eb8d7e-335c-45d8-aad1-d24a041f3440)

I need help. it says that CCMSI installer has a new update which is v1.19 but it gives me an error saying "Failed to load local installation information. cannot update." is there a fix to this? 

im on minecraft 1.20.1 with the mekanism mod version of 10.4.9.61, cc tweaked version 1.113.1, and Advanced Peripherals version 0.7.41r

**Comment by MikaylaFischler** [comment]
Just type "y" or hit enter when it prompts you that there is an update while installing something else, you shouldn't really need to directly update that way. Currently running `update` requires something to have been installed, I'll need to adjust that.

**Comment by MikaylaFischler** [comment]
Fixed, will be in the next release.
