### ISSUE TITLE
Revert Changes Not Disabled After Apply

### ISSUE THREAD

**Issue by MikaylaFischler** [MikaylaFischler/cc-mek-scada#581]
When applying redstone/peripheral configurations on the RTU, the Revert Changes button doesn't reset state if you go back. If you go home and return, it is disabled.

**Comment by LAZYsmar** [comment]
Hi, I'm a big fan of your work is there a version of this program for Minecraft 1.20.1?

**Comment by MikaylaFischler** [comment]
@LAZYsmar the program currently only has minimum requirements, which for game version is Minecraft 1.16.5. More details are in the wiki
